export default function PrivacyPolicy() {
  return (
    <main className="min-h-screen bg-[#0a0f1e] text-white px-6 py-16 max-w-4xl mx-auto">
      <a href="/" className="text-[#6798d0] text-sm hover:text-white transition-colors mb-8 block">← Back to Home</a>
      <h1 className="text-4xl font-bold mb-2">Privacy Policy</h1>
      <p className="text-gray-400 mb-2">Dynamic Human Capital Pte Ltd</p>
      <p className="text-gray-500 text-sm mb-10">Effective: 30 September 2023 · Last Updated: 4 August 2024</p>
      <p className="text-gray-300 mb-8">This Privacy Notice outlines how <strong>Dynamic Human Capital Pte Ltd ("DHC")</strong> collects, uses, discloses, and processes personal data under Singapore's <strong>Personal Data Protection Act (PDPA)</strong>.</p>
      <section className="mb-8"><h2 className="text-xl font-bold mb-3">1. Application of This Notice</h2><p className="text-gray-300">DHC collects personal data to provide recruiting and staffing services, act as an employer, and deliver HR-related services. The company requires certain personal information from candidates, job applicants, contractors, and former employees to proceed with job placement and related services.</p></section>
      <section className="mb-8"><h2 className="text-xl font-bold mb-3">2. Personal Data Collected</h2><ul className="text-gray-300 list-disc list-inside space-y-1"><li>Full name, gender, date of birth, nationality</li><li>Contact details (address, phone, email)</li><li>Resume, educational and professional qualifications</li><li>Employment history and references</li><li>Salary information and bank account details</li><li>Next-of-kin and family member details</li><li>Work-related health information and disabilities</li><li>Photographs</li></ul></section>
      <section className="mb-8"><h2 className="text-xl font-bold mb-3">3. Collection, Use, and Disclosure</h2><ul className="text-gray-300 list-disc list-inside space-y-1"><li>Assessing and evaluating your suitability for employment</li><li>Identity verification</li><li>Sharing with clients for placement opportunities</li><li>Handling inquiries and complaints</li><li>Compliance with legal obligations</li><li>Background checks and screening</li><li>Crime prevention and office security</li><li>Sending industry-relevant content and career resources</li></ul></section>
      <section className="mb-8"><h2 className="text-xl font-bold mb-3">4. Consent and Withdrawal</h2><p className="text-gray-300">Individuals may withdraw consent in writing via email to the Data Protection Officer. Withdrawal may affect job placement eligibility and office access.</p></section>
      <section className="mb-8"><h2 className="text-xl font-bold mb-3">5. Data Protection Measures</h2><p className="text-gray-300">DHC implements administrative, physical and technical measures including encryption, access controls, authentication protocols, and regular security testing to safeguard your personal data.</p></section>
      <section className="mb-8"><h2 className="text-xl font-bold mb-3">6. Personal Data Retention</h2><p className="text-gray-300">DHC retains personal data as long as necessary for stated purposes or as required by law.</p></section>
      <section className="mb-8"><h2 className="text-xl font-bold mb-3">7. International Transfers</h2><p className="text-gray-300">Personal data may be transferred outside Singapore to service providers, with appropriate legal safeguards ensuring comparable protection standards.</p></section>
      <section className="mb-8"><h2 className="text-xl font-bold mb-3">8. Data Protection Officer</h2><p className="text-gray-300 mb-2">For requests regarding access, correction, or withdrawal of consent, contact our Data Protection Officer:</p><p className="text-gray-300">Email: <a href="mailto:DPO@elitez.asia" className="text-[#6798d0] hover:text-white">DPO@elitez.asia</a></p><p className="text-gray-300 mt-2">For questions: <a href="mailto:info@dhc.com.sg" className="text-[#6798d0] hover:text-white">info@dhc.com.sg</a> · 2 Kallang Ave, CT Hub, #03-08, Singapore 339407</p></section>
    </main>
  );
}
